apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-v3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petstore-v3
  template:
    metadata:
      labels:
        app: petstore-v3
    spec:
      containers:
        - image: docker.io/swaggerapi/petstore3:unstable
          name: petstore-v3
          ports:
            - containerPort: 8080